apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
spec:
  package: haarchri/provider-aws:v0.33.0-rc.1.41.gd858eccb
  controllerConfigRef:
    name: controller-config-observe-only
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: controller-config-observe-only
spec:
  args:
    - --enable-management-policies
