apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
spec:
  package: ulucinar/provider-aws:v0.34.0-rc.0.10.gad098f2c
  controllerConfigRef:
    name: controller-config-observe-only
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: controller-config-observe-only
spec:
  args:
    - --enable-management-policies
